<a href="https://colab.research.google.com/github/LucasP01/TFG/blob/main/TFG_Lucas_Paleo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DATASET DE UBER

## Importar dataset y librerias

In [2]:
#Importamos las librerias pandas y numpy para procesar los datos e importamos seaborn para la visualizacion
import pandas as pd
import numpy as np
import seaborn as sns

print("Setup Completo")

Setup Completo

In [3]:
#Importamos el archivo desde Github
url = "https://raw.githubusercontent.com/LucasP01/TFG/refs/heads/main/ncr_ride_bookings.csv"

uber = pd.read_csv(url)

print("Carga de datos completa")

Carga de datos completa

##Analisis exploratorio de datos

In [4]:
#Visualizamos los primeros 5 registros
uber.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [8]:
#Vemos cantidad de filas y columnas
uber.shape

(150000, 21)

In [5]:
#Observamos informacion general del dataset
# Validamos los tipos de datos, la cantidad de nullos y las columnas que tenemos
uber.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [6]:
#Vemos la distribucion de las columnas numericas
uber.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,10500.0,27000.0,9000.0,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,1.0,1.0,1.0,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,0.0,0.0,0.0,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,1.0,1.0,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,1.0,1.0,1.0,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,1.0,1.0,1.0,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,1.0,1.0,1.0,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,1.0,1.0,1.0,4277.000000,50.000000,5.000000,5.000000

## Calidad de datos

Reglas para imputaciones:

Numerico continuo (promedio, distancia, calificacion, valor monetario) = rellenamos con la media poara mantener la distribucion general estable
Numericos discretos (cancelaciones, viajes incompletos) = rellenamos faltantes con 0, si no hay evento es porque no se produjo.

In [9]:
#Visualizamos los datos nulos
uber.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                                  0
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

Lo que hacemos con los nulos es lo siguiente:
- Avg VTAT usamos la media de CTAT
- Avg CTAT, Booking Value, Ride Distance y Rating con sus respectivas medias
- Las Cancelattion counts con 0
- Columnas categoricas con "none"
- Payment Method con su moda

In [16]:
uber['Avg VTAT'] = uber["Avg VTAT"].fillna(uber["Avg CTAT"].mean())
uber['Avg CTAT'] = uber["Avg CTAT"].fillna(uber["Avg CTAT"].mean())
uber['Cancelled Rides by Customer'] = uber['Cancelled Rides by Customer'].fillna(0)
uber['Reason for cancelling by Customer'] = uber['Reason for cancelling by Customer'].fillna("none")
uber['Cancelled Rides by Driver'] = uber['Cancelled Rides by Driver'].fillna(0)
uber['Driver Cancellation Reason'] = uber['Driver Cancellation Reason'].fillna("none")
uber['Incomplete Rides'] = uber['Incomplete Rides'].fillna(0)
uber['Incomplete Rides Reason'] = uber['Incomplete Rides Reason'].fillna("none")
uber['Booking Value'] = uber['Booking Value'].fillna(uber['Booking Value'].mean())
uber['Ride Distance'] = uber['Ride Distance'].fillna(uber['Ride Distance'].mean())
uber['Driver Ratings'] = uber['Driver Ratings'].fillna(uber['Driver Ratings'].mean())
uber['Customer Rating'] = uber['Customer Rating'].fillna(uber['Customer Rating'].mean())
uber['Payment Method'].fillna(uber['Payment Method'].mode()[0], inplace=True)

print("Imputacion de datos completa")

Imputacion de datos completa

/tmp/ipython-input-3928074597.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  uber['Payment Method'].fillna(uber['Payment Method'].mode()[0], inplace=True)

In [17]:
#Revisamos que esten OK los reemplazados
uber.isnull().sum()

Date                                 0
Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
Avg VTAT                             0
Avg CTAT                             0
Cancelled Rides by Customer          0
Reason for cancelling by Customer    0
Cancelled Rides by Driver            0
Driver Cancellation Reason           0
Incomplete Rides                     0
Incomplete Rides Reason              0
Booking Value                        0
Ride Distance                        0
Driver Ratings                       0
Customer Rating                      0
Payment Method                       0
dtype: int64

Para los datos asignamos los siguientes datatypes:
- Numericos : INT o Float (depende si se requieren decimales o no)
- Categorias: Category
- Fechas: datetime
- Texto: string

In [19]:
#Procedemos con los cambios del tipo de dato
uber['Date'] = pd.to_datetime(uber['Date'], errors='coerce')
uber['Time'] = pd.to_datetime(uber['Time'], format = '%H:%M:%S', errors='coerce').dt.time
uber['Booking ID'] = uber['Booking ID']. astype('string')
uber['Booking Status'] = uber['Booking Status'].astype('string')
uber['Customer ID'] = uber['Customer ID']. astype('string')
uber['Vehicle Type'] = uber['Vehicle Type']. astype('string')
uber['Pickup Location'] = uber['Pickup Location']. astype('string')
uber['Drop Location'] = uber['Drop Location']. astype('string')
uber['Cancelled Rides by Customer'] = uber['Cancelled Rides by Customer']. astype('int')
uber['Reason for cancelling by Customer'] = uber['Reason for cancelling by Customer']. astype('string')
uber['Cancelled Rides by Driver'] = uber['Cancelled Rides by Driver']. astype('int')
uber['Driver Cancellation Reason'] = uber['Driver Cancellation Reason']. astype('string')
uber['Incomplete Rides'] = uber['Incomplete Rides']. astype('int')
uber['Incomplete Rides Reason'] = uber['Incomplete Rides Reason']. astype('string')
uber['Payment Method'] = uber['Payment Method']. astype('string')

print("Cambio de datatype completo")

Cambio de datatype completo

In [20]:
#Revisamos los tipos de datos
uber.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  datetime64[ns]
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  string
 3   Booking Status                     150000 non-null  string
 4   Customer ID                        150000 non-null  string
 5   Vehicle Type                       150000 non-null  string
 6   Pickup Location                    150000 non-null  string
 7   Drop Location                      150000 non-null  string
 8   Avg VTAT                           150000 non-null  float64
 9   Avg CTAT                           150000 non-null  float64
 10  Cancelled Rides by Customer        150000 non-null  int64
 11  Reason for cancelling by Customer  150000 non-null  string
 12  Cancelled Rides by Driver          150000 non-null  int64
 13  Driver Cancellation Reason         150000 non-null  string
 14  Incomplete Rides                   150000 non-null  int64
 15  Incomplete Rides Reason            150000 non-null  string
 16  Booking Value                      150000 non-null  float64
 17  Ride Distance                      150000 non-null  float64
 18  Driver Ratings                     150000 non-null  float64
 19  Customer Rating                    150000 non-null  float64
 20  Payment Method                     150000 non-null  string
dtypes: datetime64[ns](1), float64(6), int64(3), object(1), string(10)
memory usage: 24.0+ MB

ACA Deberiamos cargar los datos a la base SQL.

##Observaciones

##Limpieza de datos

##Agregaciones

##Integracion de datos